#!/bin/bash

echo
echo Creating the nmon service account
/usr/sbin/groupadd nmon
/usr/sbin/useradd -g nmon -r -d /etc/nmon-logger -s /sbin/nologin nmon
echo
mkdir /var/log/nmon-logger; chmod 0755 /var/log/nmon-logger; chown nmon:nmon /var/log/nmon-logger
chown -R nmon:nmon /etc/nmon-logger; chmod -R 0755 /etc/nmon-logger
chown root:root /etc/cron.d/nmon-logger; chmod 0644 /etc/cron.d/nmon-logger
chown root:root /etc/logrotate.d/nmon-logger; chmod 0644 /etc/logrotate.d/nmon-logger
chown root:root /etc/syslog-ng/conf.d/nmon-logger.conf; chmod 0644 /etc/syslog-ng/conf.d/nmon-logger.conf
for log in nmon_collect.log nmon_configdata.log nmon_processing.log nmon_perfdata.log; do
touch /var/log/nmon-logger/$log
chown nmon:nmon /var/log/nmon-logger/$log
done
echo Restarting syslog-ng service:
/etc/init.d/syslog-ng restart
echo
echo Nmon logger has been successfully installed. Within next minutes, the performance and configuration data collection will start automatically.
echo Please check the content of "/var/log/nmon-logger/"
echo You will also find a new process running under nmon account, you can get the current list of running processes for the nmon account: "ps -fu nmon"
echo

exit 0