# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi machine configuration

servers=[
      {
        :hostname => "splunk",
        :ip => "192.168.33.100",
        :ram => 2048,
        :cpu => 2
      },
      {
        :hostname => "hec-client1",
        :ip => "192.168.33.101",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "hec-client2",
        :ip => "192.168.33.102",
        :ram => 512,
        :cpu => 1
      }
]

Vagrant.configure(2) do |config|

    # Get's honored normally
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # But not the centos box
    config.vm.synced_folder '.', '/home/vagrant/sync', disabled: true

    servers.each do |machine|

        config.vm.define machine[:hostname] do |node|

            config.ssh.insert_key = false
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]

            # This will be applied to all vms

            # Ubuntu
            node.vm.box = "bento/ubuntu-16.04"

            # Debian 8
            # node.vm.box = "boxcutter/debian8"

            # CentOS 7
            # node.vm.box = "boxcutter/centos73"

            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
                vb.name = machine[:hostname]
            end
        end

    end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    #ansible.inventory_path = "ansible_inventory"
    #ansible.host_key_checking = false
    #ansible.verbose = "v"
  end

end
