#!/bin/bash

echo
echo Creating the nmon service account
/usr/sbin/groupadd nmon
/usr/sbin/useradd -g nmon -r -d /etc/nmon-logger -s /sbin/nologin nmon
echo
echo Restarting rsyslog service:
service rsyslog restart
echo
echo Nmon logger has been successfully installed. Within next minutes, the performance and configuration data collection will start automatically.
echo Please check the content of "/var/log/nmon-logger/"
echo You will also find a new process running under nmon account, you can get the current list of running processes for the nmon account: "ps -fu nmon"
echo

exit 0
