#!/bin/bash

echo
if [ `ps -fu nmon | grep -v 'PID' | wc -l` -ne 0 ]; then echo "Killing running nmon processes:"; echo "**** list of running processes: ****"; echo `ps -fu nmon | grep '/etc/nmon-logger'`; ps -fu nmon | grep '/etc/nmon-logger/bin/linux' | awk '{print $2}' | xargs kill; fi
echo "Removing /etc/nmon-logger remaining files."; rm -rf /etc/nmon-logger
echo "Removing /var/log/nmon-logger remaining files."; rm -rf /var/log/nmon-logger
echo "Removing nmon user account"; userdel nmon
echo Restarting rsyslog service:
service rsyslog restart
echo
echo Nmon logger has been successfully uninstalled.
echo

exit 0
